In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

Create a vector of 200 random integers between 1 and 100


In [3]:
v1=np.random.randint(1,100,200)

Display the vector

In [4]:
v1

array([22, 25, 61, 52, 35, 48, 70, 41, 69,  8, 75, 19, 59, 27, 67, 69, 99,
       12, 52, 46, 22, 31, 43, 82, 22, 90, 97, 14, 56, 90, 13, 56, 65, 66,
       96,  3,  5, 58, 70, 42, 51, 88, 75, 75, 75, 56, 55, 28, 73, 53, 47,
       14, 16, 78, 70, 91, 12, 93, 82, 46, 46, 35,  5, 18, 93,  3, 37, 99,
       58, 33, 56,  1, 78, 69, 82, 95, 21, 87, 86, 37, 20, 62, 84, 75, 24,
       97, 54, 15,  1, 57,  1, 13, 45, 47, 70, 77, 50, 35,  3, 74, 86, 51,
       91, 63, 92, 21, 82, 63, 54,  8, 96, 95, 94, 16, 37, 95, 17, 96, 85,
       92, 45, 27, 94, 64, 62,  3, 10, 27, 84, 44, 52, 93, 70, 45, 53, 84,
       40, 14, 32, 36, 81, 14, 44, 10, 97, 73, 89, 19, 66, 35, 34, 67, 10,
       27,  5, 16, 44, 33,  7, 56, 48, 46,  3, 63, 79, 49, 40, 57,  9, 64,
        5, 31, 16, 82, 67, 84, 13, 75, 34, 81, 55,  3, 68,  5, 27, 12, 54,
       20, 85, 67, 28, 65, 48, 99, 53, 14, 42, 16, 98, 35])

Pick out the first 10 values

In [5]:
v1[:10]

array([22, 25, 61, 52, 35, 48, 70, 41, 69,  8])

Pick out the last value

In [6]:
v1[-1]

35

Pickout the last 10 values

In [7]:
v1[-10:]

array([28, 65, 48, 99, 53, 14, 42, 16, 98, 35])

Pickout every 3rd value

In [8]:
v1[::3]

array([22, 52, 70,  8, 59, 69, 52, 31, 22, 14, 13, 66,  5, 42, 75, 56, 73,
       14, 70, 93, 46, 18, 37, 33, 78, 95, 86, 62, 24, 15,  1, 47, 50, 74,
       91, 21, 54, 95, 37, 96, 45, 64, 10, 44, 70, 84, 32, 14, 97, 19, 34,
       27, 44, 56,  3, 49,  9, 31, 67, 75, 55,  5, 54, 67, 48, 14, 98])

generate an array of the frist 10 fibronaaci sequecne numbers

In [9]:
vf=np.zeros(10,dtype=np.int64)

In [10]:
vf[0:2]=[1,2]
for idx in range(2,10):
    vf[idx]=vf[idx-2]+vf[idx-1]

In [11]:
vf

array([ 1,  2,  3,  5,  8, 13, 21, 34, 55, 89])

Use that sequnece to index the array v1

In [12]:
v1[vf]

array([25, 61, 52, 48, 69, 27, 31, 96, 91, 57])

generate an array of values for v1 that is less than 20

In [13]:
v1[v1<20]

array([ 8, 19, 12, 14, 13,  3,  5, 14, 16, 12,  5, 18,  3,  1, 15,  1,  1,
       13,  3,  8, 16, 17,  3, 10, 14, 14, 10, 19, 10,  5, 16,  7,  3,  9,
        5, 16, 13,  3,  5, 12, 14, 16])

generate a boolean array the same length as v1 where each value in the array is true if v1<20 and false if it is not

In [14]:
vb = v1<20

In [15]:
vb

array([False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False,

count how many values are true

In [16]:
vb.sum()

42

generate a boolean array the same length as vq where each value is true if v1>10

In [17]:
vb2 = v1>10

In [18]:
vb2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,

generate an array that ands each array value by value

In [19]:
vb &vb2

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

generate an array that is the values of v1 acccording to that array

In [20]:
v1[vb&vb2]

array([19, 12, 14, 13, 14, 16, 12, 18, 15, 13, 16, 17, 14, 14, 19, 16, 16,
       13, 12, 14, 16])

generate an array the same length of v1 that would be its index

In [21]:
vi = np.arange(len(v1))

In [22]:
vi

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

find the index where vb&v2 are true in v1

In [23]:
vi[vb&vb2]

array([ 11,  17,  27,  30,  51,  52,  56,  63,  87,  91, 113, 116, 137,
       141, 147, 155, 172, 176, 185, 195, 197])